# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-758e76c9-2be7-4008-92fa-cd78f7f2ea1c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-758e76c9-2be7-4008-92fa-cd78f7f2ea1c".device = "/dev/disk/by-uuid/758e76c9-2be7-4008-92fa-cd78f7f2ea1c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B652-F5CD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c4892993-c483-4bc4-afeb-0549d71d2959"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
