# Do not modify this file! It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "usbhid"
    "sd_mod"
    "sdhci_pci"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

   fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "ext4";
  };

   boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/630ca97f-16bb-4020-9838-fc394df6d5ac";
  };

    fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8B43-B2C7";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-label/datastore";
    fsType = "ext4";
    options = [ "defaults" "nofail" "noatime" ];
  };

      swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 24 * 1024;   # 24 ГиБ = 24576 МиБ — должно точно совпадать
                          # с реальным размером файла, иначе NixOS пересоздаст
    }
  ];

  # === Гибернация (resume с LUKS) ===
  # Указываем устройство, с которого система будет читать образ памяти
  # после гибернации. Это расшифрованный swap на LUKS.
#   boot.resumeDevice = "/dev/mapper/luks-c4892993-c483-4bc4-afeb-0549d71d2959"; #swap?

  # Включаем поддержку гибернации в NixOS.
#   powerManagement.enable = true;


# Запрещаем systemd использовать гибернацию на уровне системы.
# Это делает невозможным вызов `systemctl hibernate` и подобных команд.
systemd.sleep.settings.Sleep = {
  AllowHibernation = "no";
  AllowHybridSleep = "no";
  AllowSuspendThenHibernate = "no";
};

# Запрещаем любым приложениям инициировать гибернацию через polkit.
# Это предотвращает случайный запуск гибернации из меню.
security.polkit.extraConfig = ''
  polkit.addRule(function(action, subject) {
      if (action.id == "org.freedesktop.login1.hibernate" ||
          action.id == "org.freedesktop.login1.hibernate-multiple-sessions") {
          return polkit.Result.NO;
      }
  });
'';

# Игнорируем нажатие аппаратной клавиши гибернации.
services.logind.settings.Login.HandleHibernateKey = "ignore";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
